Add item requests
albertleinsoo/java-shareit pull request #3
Opened 2023-08-06 21:24 UTC by albertleinsoo

2023-08-08 21:11 UTC, alexache requested changes

2023-08-08 21:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        assertNotNull(bookingDtoOutputSaved);
Может немного больше верификаций результата?

2023-08-08 21:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/request/RequestControllerTest.java
> +    }
Немного не хватает негативный сценариев с непрошедшими валидациями

2023-08-08 21:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    UserDto userDto;
Не хватает модификатора доступа у поля

2023-08-09 21:37 UTC, albertleinsoo commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void findByBooker_Id() {
Раз они уже есть, можно оставить, думаю?

2023-08-09 21:39 UTC, albertleinsoo commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        itemRequestOutput.forEach(itemRequest -> itemRequest.setItems(findItemsByRequestId(itemRequest.getId())));
Не могу понять, как сформировать запрос и потом реализовать метод без использования цикла. В виде, собственно, цикла или map

2023-08-10 20:38 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void findByBooker_Id() {
Естественно, больше не меньше

2023-08-10 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        itemRequestOutput.forEach(itemRequest -> itemRequest.setItems(findItemsByRequestId(itemRequest.getId())));
Этот комментарий остался в силе, я в пачке немного расписал возможные решения

2023-08-10 20:49 UTC, alexache requested changes

2023-08-10 20:49 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        Request request = requestRepository.findById(requestId).orElseThrow(() -> new ObjectNotFoundException("Failed to process request. User with id = " + requestId + " doesn't exist."));
От запросов к базе в цикле все ещё нужно избавиться

2023-08-12 09:50 UTC, alexache approved these changes

2023-08-12 11:12 UTC, merged