add: docker services
albertleinsoo/java-shareit pull request #4
Opened 2023-08-14 12:14 UTC by albertleinsoo

2023-08-14 19:32 UTC, alexache requested changes

2023-08-14 19:32 UTC, alexache commented on docker-compose.yml
> +#      - TZ=Europe/Moscow
Комментарии лучше подчищать

2023-08-14 19:32 UTC, alexache commented on docker-compose.yml
> +      - SPRING_DATASOURCE_USERNAME=root
Как-то много переменных об одном и том же

2023-08-14 19:32 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +        Map<String, Object> parameters = Map.of(
Мапа из одного элемента не имеет большого смысла, можно обойтись без мапы

2023-08-14 19:32 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/request/RequestController.java
> +        if (from != null && size != null) {
Почему в каких-то контроллерах через аннотации, а в каких-то явные проверки?

2023-08-14 19:32 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<BookingDtoOutput> add(@RequestHeader("X-Sharer-User-Id")Integer userId,
ResponseEntity не обязательны

2023-08-14 19:32 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDtoInput.java
>      @FutureOrPresent
Никаких валидаций не должно оставаться в модуле сервиса

2023-08-14 19:32 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @Email
Валидаций не должно быть

2023-08-14 21:31 UTC, albertleinsoo commented on docker-compose.yml
> +#      - TZ=Europe/Moscow
Строчки с TimeZone закомментированы, т.к. на локальном компьютере они нужны для корректной работы тестов.

2023-08-15 20:12 UTC, alexache approved these changes

2023-08-15 20:14 UTC, merged